[project]
name = "team-roster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.6"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "pandas>=2.2.3",
    "pydantic>=2.11.3",
]
